spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost/user_service

  jpa:
    hibernate:
      ddl-auto: create